# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
            args:
              WWWGROUP: '${WWWGROUP}'
              WWWUSER: '${WWWUSER}'
        ports:
          - '${APP_PORT:-80}:80'
          - '${APP_SSL_PORT:-443}:443'
          - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
          - '${VITEST_UI_PORT:-5174}:${VITEST_UI_PORT:-5174}'
        environment:
          ENABLE_XDEBUG: '${ENABLE_XDEBUG:-no}'
          TRUSTED_PROXIES: "*"
        volumes:
          - './:/var/www/html/'
          - './ssl:/local/certs/'
        depends_on:
          - db
    db:
      image: 'mariadb:10'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - 'mariadb:/var/lib/mysql'
        - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-u${DB_USERNAME}", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 5s
    mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - '${FORWARD_PHPMYADMIN_PORT:-8888}:80'
      environment:
        MYSQL_USERNAME: "${DB_USERNAME}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        PMA_HOST: db
        PMA_USER: "${DB_USERNAME}"
        PMA_PASSWORD: "${DB_PASSWORD}"
        UPLOAD_LIMIT: 2G
    openldap:
      image: osixia/openldap
      environment:
        LDAP_ORGANISATION: "Demo University"
        LDAP_DOMAIN: "university.org"
        LDAP_READONLY_USER: 'true'
      volumes:
        - './docker/openldap:/container/service/slapd/assets/config/bootstrap/ldif/custom'
      command: --copy-service
    phpldapadmin:
      image: osixia/phpldapadmin
      links:
        - openldap:ldap-host
      ports:
        - '${FORWARD_PHPLDAPADMIN_PORT:-6680}:80'
      environment:
        PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-host': [{'server': []},{'login': [{'bind_id': 'cn=admin,dc=university,dc=org', 'bind_pass': 'admin'}]}]}]"
        PHPLDAPADMIN_HTTPS: 'false'
    postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
    keycloak:
        image: quay.io/keycloak/keycloak:legacy
        environment:
          DB_VENDOR: POSTGRES
          DB_ADDR: postgres
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_SCHEMA: public
          DB_PASSWORD: password
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: Pa55w0rd
          #KEYCLOAK_LOGLEVEL: ALL
          # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
          #JDBC_PARAMS: "ssl=true"
        ports:
          - 8080:8080
        depends_on:
          - postgres
volumes:
  mariadb:
    driver: local
  postgres_data:
    driver: local
